# This is a sample file; it will be overridden by local/config/emeraldview.yml
# See http://yitznewton/emeraldview/index.php/Customization for documentation

emeraldview_name:          Wassamatta Digital Collections
institution_url:           http://wassamatta-u.example.com/library/
institution_name:          Wassamatta University Libraries

greenstone_collection_dir: files

default_theme: default
default_language: en
languages:
  en: English
  fr: French

collections:
  demo:
    active: true
    slug_max_length: 30
    slug_spacer: "-"
    slug_metadata_elements:
      - Title
      - Subject
    slug_stopwords:
      - a
      - an
      - the
      - of
      - and
    document_tree_format: "[Title]"
    search_hits_per_page: 20
    search_results_format: "[Title]"
    search_history_length: 5
    classifiers:
      CL2:
        format:
          branch: "[Title] ([numleafdocs])"
          leaf:   "[Title]"
      CL4:
        format: "[dls.Keyword]"
    display_metadata:
      Title: Title
      Author: Author
