emeraldview_name:          Wassamatta Digital Collections
institution_url:           http://wassamatta-u.example.com/library/
institution_name:          Wassamatta University Libraries

greenstone_collection_dir: /www/websites/collect

default_theme: default
default_language: en
languages:
  en: English
  fr: French
  he: עברית

collections:
  demo:
    active: true
    slug_max_length: 30
    slug_spacer: "-"
    slug_metadata_elements:
      - Title
      - Subject
    slug_stopwords:
      - a
      - an
      - the
      - of
      - and
    document_tree_format: "[Title]"
    classifiers:
      CL1:
        format:
          branch: "[Title] ([numleafdocs])"
          leaf:   "[Title]"
    display_metadata:
      Title: Title
      Author: Author
    
  paged:
    active: true

  that:
    active: false
